---
title: "pviot"
author: "tthejll"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r library}
library(tidyverse)


```

Pivot
```{r create data}

data_df <- tibble(id = 1:20,
                  age = sample(20:80, 20, replace = TRUE),
                  sex = sample(c("M", "F", "Not specified"), 20, prob = c(0.48, 0.49, 0.03), replace = TRUE),
                  Q_1 = round(runif(n = 20, min = 1, max = 12)),
                  Q_2 = round(runif(n = 20, min = 1, max = 15)),
                  Q_3 = round(runif(n = 20, min = 1, max = 7)),
                  Q_4 = round(runif(n = 20, min = 1, max = 12)),
                  Q_5 = round(runif(n = 20, min = 1, max = 13)))

data_df %>% print()

```

First thing is I want to create id as a factor

``` {r manipulate}

data_df <- data_df %>%
  mutate(id = as.factor(id),
         sex = as.factor(sex))

data_df %>% print()

```


Now I want to pivot to long:

``` {r pivot long}

data_long <- data_df %>%
  pivot_longer(names_to = "Question", values_to = "Answer")
```


``` {r pivot long}

data_long <- data_df %>%
  pivot_longer(everything(), names_to = "Question", values_to = "Answer")

```


``` {r pivot long}

data_long <- data_df %>%
  pivot_longer(cols = !id, names_to = "Question", values_to = "Answer")

```

``` {r pivot long}

data_long <- data_df %>%
  pivot_longer(cols = !c(id,sex), names_to = "Question", values_to = "Answer")

data_long %>% print()
```


``` {r pivot long}

data_long <- data_df %>%
  pivot_longer(cols = !c(id,sex, age), names_to = "Question", values_to = "Answer")

data_long %>% print()
```